<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net6.0-windows7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<ApplicationIcon>Icons\mcsmenu.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="Icons\mcsmenu.ico" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="Models\CommandDefinition.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="NickBuhro.Translit" Version="1.0.0" />
	</ItemGroup>

</Project>
